@startuml
participant "Client" as c
participant "Local \nNameServer" as lns

participant "root \nNameServer" as rns
participant "edu \nNameServer" as tldns
participant "googleplex.edu \nNameServer" as dns
participant "compsci.googleplex.edu \nNameServer" as sns

c->c: Check Resolver Cache
c->lns: Recursive Query
activate lns
lns->lns: Check Cache
lns->rns: Iterative Query to root
rns-->lns: Name Server for .edu
lns->tldns: Iterative Query to .edu
tldns-->lns: Name Server for googleplex.edu
lns->dns: Iterative Query to googleplex.edu
dns-->lns: Name Server for compsci.googleplex.edu
lns->sns: Iterative Query to compsci.googleplex.edu
sns-->lns: IP Address for www.net.compsci.googleplex.edu
lns->lns: Update Cache
lns-->c: Requested IP Address
deactivate lns
c->c: Update Cache

@enduml
