@startuml
participant "Client" as c
participant "Server" as s

== TCP Establishment==
c->s: [SYN] Seq=x
note left: SYN_SENT\n(connect())
note right: LISTEN\n(listen())
s->c: [SYN, ACK] Seq=y, ACK=x+1
note right: SYN_RCVD
note left: ESTABLISHED
c->s: [ACK] Seq=x+1, ACK y+1
note right: ESTABLISHED
== Data Exchange ==
note left c: write() starts
c->s: Application data\n[PSH, ACK] Seq=x+1, ACK=y+1
note left c: write() returns\nread() starts
s-->c: [ACK] Seq=y+1, ACK=a(x+Len)
s->c: Application data\n[PSH, ACK] Seq=y+1, ACK=a(x+Len)
note left c: read() returns
c-->s: [ACK] Seq=a, ACK=b(y+1+Len)
==TCP Termination==
c->s: [FIN, ACK] Seq=a, ACK=b(y+1+Len)
note left: FIN_WAIT_1
note right: CLOSE_WAIT
s->c: [ACK] Seq=b, ACK=a+1
note left: FIN_WAIT_2
s->c: [FIN] Seq=b, ACK=a+1
note right: LAST_ACK
note left: TIME_WAIT
c->s: [ACK] Seq=a, ACK=b+1


@enduml
